set -g mouse on

set-option -g base-index 1
set-option -g pane-base-index 1

# 'PREFIX r' to reload of the config file
unbind r
bind-key r source-file ~/.tmux.conf\; display-message '~/.tmux.conf reloaded'

# split panes using | and -
bind-key | split-window -h
bind-key - split-window -v
unbind '"'
unbind %

# set limit
set-option -g history-limit 1000
set-option -g display-panes-time 2000


# DESIGN TWEAKS
# don't do anything when a 'bell' rings
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-option -g monitor-activity off
set-option -g bell-action none

#set-option -g pane-border-status bottom
#set-option -g pane-border-format ""
#set-option -g status-left-length 100
#set-option -g status-right-length 100

run-shell "~/.tmux/themes/tokyo-night-tmux/tokyo-night-tmux.tmux"
